export const CONNECTING = 'CONNECTING';
export const CONNECTED = 'CONNECTED';
export const CONNECTION_FAILED = 'CONNECTION_FAILED';
export const DISCONNECTING = 'DISCONNECTING';
export const DISCONNECTED = 'DISCONNECTED';
export const DISCONNECTION_FAILED = 'DISCONNECTION_FAILED';
